--
-- PostgreSQL database dump
--

-- Dumped from database version 13.15 (Debian 13.15-1.pgdg120+1)
-- Dumped by pg_dump version 13.15 (Debian 13.15-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: documento_transferencia; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.documento_transferencia (
    id bigint NOT NULL,
    procedimentos_acondicionamento character varying(255)[],
    procedimentos_recebimento character varying(255)[]
);


ALTER TABLE public.documento_transferencia OWNER TO admin;

--
-- Name: documento_transferencia_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.documento_transferencia ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.documento_transferencia_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: documento_transferencia_medicamento; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.documento_transferencia_medicamento (
    documento_transferencia_id bigint NOT NULL,
    medicamento_id bigint NOT NULL
);


ALTER TABLE public.documento_transferencia_medicamento OWNER TO admin;

--
-- Name: endereco; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.endereco (
    estado character(8) NOT NULL,
    cep character(8) NOT NULL,
    id bigint NOT NULL,
    bairro character varying(50) NOT NULL,
    cidade character varying(50) NOT NULL,
    complemento character varying(100),
    rua character varying(100) NOT NULL
);


ALTER TABLE public.endereco OWNER TO admin;

--
-- Name: endereco_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.endereco ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.endereco_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: especialidade; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.especialidade (
    id bigint NOT NULL,
    descricao character varying(255),
    nome character varying(255) NOT NULL
);


ALTER TABLE public.especialidade OWNER TO admin;

--
-- Name: especialidade_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.especialidade ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.especialidade_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: medicamento; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.medicamento (
    id bigint NOT NULL,
    descricao character varying(255),
    nome character varying(255) NOT NULL,
    principio_ativo character varying(255)
);


ALTER TABLE public.medicamento OWNER TO admin;

--
-- Name: medicamento_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.medicamento ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.medicamento_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: medicamento_prescrito; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.medicamento_prescrito (
    dosagem double precision,
    id bigint NOT NULL,
    medicamento_id bigint NOT NULL,
    posologia character varying(255),
    unidade_dosagem character varying(255),
    via_administracao character varying(255),
    CONSTRAINT medicamento_prescrito_unidade_dosagem_check CHECK (((unidade_dosagem)::text = ANY ((ARRAY['mg'::character varying, 'µg'::character varying, 'mL'::character varying, 'cp'::character varying, 'UI'::character varying])::text[])))
);


ALTER TABLE public.medicamento_prescrito OWNER TO admin;

--
-- Name: medicamento_prescrito_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.medicamento_prescrito ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.medicamento_prescrito_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: medico; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.medico (
    papel smallint NOT NULL,
    especialidade_id bigint NOT NULL,
    id bigint NOT NULL,
    unidade_hospitalar_id bigint NOT NULL,
    user_id bigint,
    crm character varying(255) NOT NULL,
    nome character varying(255) NOT NULL,
    telefone character varying(255) NOT NULL,
    CONSTRAINT medico_papel_check CHECK (((papel >= 0) AND (papel <= 1)))
);


ALTER TABLE public.medico OWNER TO admin;

--
-- Name: medico_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.medico ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.medico_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: paciente; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.paciente (
    tipo_sanguineo smallint NOT NULL,
    endereco_id bigint,
    id bigint NOT NULL,
    prontuario_id bigint NOT NULL,
    cpf character varying(255) NOT NULL,
    email character varying(255),
    name character varying(255) NOT NULL,
    telefone character varying(255),
    CONSTRAINT paciente_tipo_sanguineo_check CHECK (((tipo_sanguineo >= 0) AND (tipo_sanguineo <= 7)))
);


ALTER TABLE public.paciente OWNER TO admin;

--
-- Name: paciente_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.paciente ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.paciente_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: prontuario; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.prontuario (
    id bigint NOT NULL,
    classificacao character varying(255),
    CONSTRAINT prontuario_classificacao_check CHECK (((classificacao)::text = ANY ((ARRAY['PRIMARIA'::character varying, 'SECUNDARIA'::character varying, 'TERCIARIA'::character varying])::text[])))
);


ALTER TABLE public.prontuario OWNER TO admin;

--
-- Name: prontuario_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.prontuario ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.prontuario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: prontuario_medicamento_prescrito; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.prontuario_medicamento_prescrito (
    medicamento_prescrito_id bigint NOT NULL,
    prontuario_id bigint NOT NULL
);


ALTER TABLE public.prontuario_medicamento_prescrito OWNER TO admin;

--
-- Name: role; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.role (
    id bigint NOT NULL,
    role character varying(255),
    CONSTRAINT role_role_check CHECK (((role)::text = ANY ((ARRAY['ROLE_ADMIN'::character varying, 'ROLE_MEDICO'::character varying, 'ROLE_MEDICO_REGULADOR'::character varying, 'ROLE_USUARIO'::character varying])::text[])))
);


ALTER TABLE public.role OWNER TO admin;

--
-- Name: role_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.role ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: solicitacao; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.solicitacao (
    documento_id bigint NOT NULL,
    horario_solicitacao timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    medico_id bigint NOT NULL,
    paciente_id bigint NOT NULL,
    motivo character varying(255)
);


ALTER TABLE public.solicitacao OWNER TO admin;

--
-- Name: solicitacao_especialidade; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.solicitacao_especialidade (
    especialidade_id bigint NOT NULL,
    solicitacao_id bigint NOT NULL
);


ALTER TABLE public.solicitacao_especialidade OWNER TO admin;

--
-- Name: solicitacao_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.solicitacao ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.solicitacao_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: transferencia; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.transferencia (
    distancia double precision,
    destino_id bigint NOT NULL,
    documento_transferencia_id bigint NOT NULL,
    horario_previsto_chegada timestamp(6) without time zone,
    horario_saida timestamp(6) without time zone,
    id bigint NOT NULL,
    medico_destino_id bigint,
    medico_origem_id bigint NOT NULL,
    medico_regulador_id bigint NOT NULL,
    origem_id bigint NOT NULL,
    paciente_id bigint NOT NULL,
    solicitacao_id bigint NOT NULL,
    meio_transporte character varying(20),
    CONSTRAINT transferencia_meio_transporte_check CHECK (((meio_transporte)::text = ANY ((ARRAY['AMBULANCIA'::character varying, 'HELICOPTERO'::character varying, 'AVIAO'::character varying, 'EVTOL'::character varying])::text[])))
);


ALTER TABLE public.transferencia OWNER TO admin;

--
-- Name: transferencia_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.transferencia ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transferencia_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: unidade_hospitalar; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.unidade_hospitalar (
    disponibilidade_leitos integer NOT NULL,
    latitude double precision NOT NULL,
    longitude double precision NOT NULL,
    temuti boolean NOT NULL,
    endereco_id bigint NOT NULL,
    id bigint NOT NULL,
    dados_pessoal character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    telefone character varying(255) NOT NULL
);


ALTER TABLE public.unidade_hospitalar OWNER TO admin;

--
-- Name: unidade_hospitalar_especialidades; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.unidade_hospitalar_especialidades (
    especialidade_id bigint NOT NULL,
    unidade_hospitalar_id bigint NOT NULL
);


ALTER TABLE public.unidade_hospitalar_especialidades OWNER TO admin;

--
-- Name: unidade_hospitalar_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.unidade_hospitalar ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.unidade_hospitalar_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_roles; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.user_roles (
    role_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.user_roles OWNER TO admin;

--
-- Name: users; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.users (
    enabled boolean NOT NULL,
    id bigint NOT NULL,
    password character varying(255) NOT NULL,
    username character varying(255) NOT NULL
);


ALTER TABLE public.users OWNER TO admin;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: documento_transferencia; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.documento_transferencia (id, procedimentos_acondicionamento, procedimentos_recebimento) FROM stdin;
\.


--
-- Data for Name: documento_transferencia_medicamento; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.documento_transferencia_medicamento (documento_transferencia_id, medicamento_id) FROM stdin;
\.


--
-- Data for Name: endereco; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.endereco (estado, cep, id, bairro, cidade, complemento, rua) FROM stdin;
\.


--
-- Data for Name: especialidade; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.especialidade (id, descricao, nome) FROM stdin;
\.


--
-- Data for Name: medicamento; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.medicamento (id, descricao, nome, principio_ativo) FROM stdin;
\.


--
-- Data for Name: medicamento_prescrito; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.medicamento_prescrito (dosagem, id, medicamento_id, posologia, unidade_dosagem, via_administracao) FROM stdin;
\.


--
-- Data for Name: medico; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.medico (papel, especialidade_id, id, unidade_hospitalar_id, user_id, crm, nome, telefone) FROM stdin;
\.


--
-- Data for Name: paciente; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.paciente (tipo_sanguineo, endereco_id, id, prontuario_id, cpf, email, name, telefone) FROM stdin;
\.


--
-- Data for Name: prontuario; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.prontuario (id, classificacao) FROM stdin;
\.


--
-- Data for Name: prontuario_medicamento_prescrito; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.prontuario_medicamento_prescrito (medicamento_prescrito_id, prontuario_id) FROM stdin;
\.


--
-- Data for Name: role; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.role (id, role) FROM stdin;
1	ROLE_ADMIN
\.


--
-- Data for Name: solicitacao; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.solicitacao (documento_id, horario_solicitacao, id, medico_id, paciente_id, motivo) FROM stdin;
\.


--
-- Data for Name: solicitacao_especialidade; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.solicitacao_especialidade (especialidade_id, solicitacao_id) FROM stdin;
\.


--
-- Data for Name: transferencia; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.transferencia (distancia, destino_id, documento_transferencia_id, horario_previsto_chegada, horario_saida, id, medico_destino_id, medico_origem_id, medico_regulador_id, origem_id, paciente_id, solicitacao_id, meio_transporte) FROM stdin;
\.


--
-- Data for Name: unidade_hospitalar; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.unidade_hospitalar (disponibilidade_leitos, latitude, longitude, temuti, endereco_id, id, dados_pessoal, email, telefone) FROM stdin;
\.


--
-- Data for Name: unidade_hospitalar_especialidades; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.unidade_hospitalar_especialidades (especialidade_id, unidade_hospitalar_id) FROM stdin;
\.


--
-- Data for Name: user_roles; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.user_roles (role_id, user_id) FROM stdin;
1	1
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.users (enabled, id, password, username) FROM stdin;
t	1	$2a$10$4/.l3nbySMoS80P.cpvT6.SVMzRRNRn0FfnxXLxOovz16jbVb/yly	admin
\.


--
-- Name: documento_transferencia_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.documento_transferencia_id_seq', 1, false);


--
-- Name: endereco_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.endereco_id_seq', 1, false);


--
-- Name: especialidade_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.especialidade_id_seq', 1, false);


--
-- Name: medicamento_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.medicamento_id_seq', 1, false);


--
-- Name: medicamento_prescrito_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.medicamento_prescrito_id_seq', 1, false);


--
-- Name: medico_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.medico_id_seq', 1, false);


--
-- Name: paciente_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.paciente_id_seq', 1, false);


--
-- Name: prontuario_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.prontuario_id_seq', 1, false);


--
-- Name: role_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.role_id_seq', 1, true);


--
-- Name: solicitacao_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.solicitacao_id_seq', 1, false);


--
-- Name: transferencia_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.transferencia_id_seq', 1, false);


--
-- Name: unidade_hospitalar_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.unidade_hospitalar_id_seq', 1, false);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.users_id_seq', 1, true);


--
-- Name: documento_transferencia documento_transferencia_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.documento_transferencia
    ADD CONSTRAINT documento_transferencia_pkey PRIMARY KEY (id);


--
-- Name: endereco endereco_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.endereco
    ADD CONSTRAINT endereco_pkey PRIMARY KEY (id);


--
-- Name: especialidade especialidade_nome_key; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.especialidade
    ADD CONSTRAINT especialidade_nome_key UNIQUE (nome);


--
-- Name: especialidade especialidade_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.especialidade
    ADD CONSTRAINT especialidade_pkey PRIMARY KEY (id);


--
-- Name: medicamento medicamento_nome_key; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.medicamento
    ADD CONSTRAINT medicamento_nome_key UNIQUE (nome);


--
-- Name: medicamento medicamento_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.medicamento
    ADD CONSTRAINT medicamento_pkey PRIMARY KEY (id);


--
-- Name: medicamento_prescrito medicamento_prescrito_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.medicamento_prescrito
    ADD CONSTRAINT medicamento_prescrito_pkey PRIMARY KEY (id);


--
-- Name: medico medico_crm_key; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.medico
    ADD CONSTRAINT medico_crm_key UNIQUE (crm);


--
-- Name: medico medico_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.medico
    ADD CONSTRAINT medico_pkey PRIMARY KEY (id);


--
-- Name: medico medico_user_id_key; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.medico
    ADD CONSTRAINT medico_user_id_key UNIQUE (user_id);


--
-- Name: paciente paciente_cpf_key; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.paciente
    ADD CONSTRAINT paciente_cpf_key UNIQUE (cpf);


--
-- Name: paciente paciente_endereco_id_key; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.paciente
    ADD CONSTRAINT paciente_endereco_id_key UNIQUE (endereco_id);


--
-- Name: paciente paciente_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.paciente
    ADD CONSTRAINT paciente_pkey PRIMARY KEY (id);


--
-- Name: paciente paciente_prontuario_id_key; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.paciente
    ADD CONSTRAINT paciente_prontuario_id_key UNIQUE (prontuario_id);


--
-- Name: prontuario prontuario_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.prontuario
    ADD CONSTRAINT prontuario_pkey PRIMARY KEY (id);


--
-- Name: role role_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.role
    ADD CONSTRAINT role_pkey PRIMARY KEY (id);


--
-- Name: solicitacao solicitacao_documento_id_key; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.solicitacao
    ADD CONSTRAINT solicitacao_documento_id_key UNIQUE (documento_id);


--
-- Name: solicitacao solicitacao_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.solicitacao
    ADD CONSTRAINT solicitacao_pkey PRIMARY KEY (id);


--
-- Name: transferencia transferencia_documento_transferencia_id_key; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.transferencia
    ADD CONSTRAINT transferencia_documento_transferencia_id_key UNIQUE (documento_transferencia_id);


--
-- Name: transferencia transferencia_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.transferencia
    ADD CONSTRAINT transferencia_pkey PRIMARY KEY (id);


--
-- Name: transferencia transferencia_solicitacao_id_key; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.transferencia
    ADD CONSTRAINT transferencia_solicitacao_id_key UNIQUE (solicitacao_id);


--
-- Name: unidade_hospitalar unidade_hospitalar_endereco_id_key; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.unidade_hospitalar
    ADD CONSTRAINT unidade_hospitalar_endereco_id_key UNIQUE (endereco_id);


--
-- Name: unidade_hospitalar unidade_hospitalar_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.unidade_hospitalar
    ADD CONSTRAINT unidade_hospitalar_pkey PRIMARY KEY (id);


--
-- Name: user_roles user_roles_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT user_roles_pkey PRIMARY KEY (role_id, user_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: users users_username_key; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_username_key UNIQUE (username);


--
-- Name: transferencia fk53oysk5w92lmi38mln25cpyu; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.transferencia
    ADD CONSTRAINT fk53oysk5w92lmi38mln25cpyu FOREIGN KEY (paciente_id) REFERENCES public.paciente(id);


--
-- Name: documento_transferencia_medicamento fk5fymqmt37iuma9nbo5buleiyp; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.documento_transferencia_medicamento
    ADD CONSTRAINT fk5fymqmt37iuma9nbo5buleiyp FOREIGN KEY (documento_transferencia_id) REFERENCES public.documento_transferencia(id);


--
-- Name: prontuario_medicamento_prescrito fk5u2teuokli8k2hfgdeuk5g4jj; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.prontuario_medicamento_prescrito
    ADD CONSTRAINT fk5u2teuokli8k2hfgdeuk5g4jj FOREIGN KEY (medicamento_prescrito_id) REFERENCES public.medicamento_prescrito(id);


--
-- Name: unidade_hospitalar_especialidades fk5x97ljawo49nlceams0garlgu; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.unidade_hospitalar_especialidades
    ADD CONSTRAINT fk5x97ljawo49nlceams0garlgu FOREIGN KEY (unidade_hospitalar_id) REFERENCES public.unidade_hospitalar(id);


--
-- Name: medico fka38dmbx2nluc8fuh8dfw0ngf1; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.medico
    ADD CONSTRAINT fka38dmbx2nluc8fuh8dfw0ngf1 FOREIGN KEY (unidade_hospitalar_id) REFERENCES public.unidade_hospitalar(id);


--
-- Name: documento_transferencia_medicamento fkb2r12je7sr44a1uwaglv3av1i; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.documento_transferencia_medicamento
    ADD CONSTRAINT fkb2r12je7sr44a1uwaglv3av1i FOREIGN KEY (medicamento_id) REFERENCES public.medicamento(id);


--
-- Name: solicitacao_especialidade fkdt9gyxi86y06b3sgujanqvwmp; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.solicitacao_especialidade
    ADD CONSTRAINT fkdt9gyxi86y06b3sgujanqvwmp FOREIGN KEY (solicitacao_id) REFERENCES public.solicitacao(id);


--
-- Name: transferencia fkdwrwrvchihqq6o3muidu5yvmb; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.transferencia
    ADD CONSTRAINT fkdwrwrvchihqq6o3muidu5yvmb FOREIGN KEY (medico_regulador_id) REFERENCES public.medico(id);


--
-- Name: user_roles fkhfh9dx7w3ubf1co1vdev94g3f; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fkhfh9dx7w3ubf1co1vdev94g3f FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: transferencia fkip2kreeti9mgf4tg4gyoxfvca; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.transferencia
    ADD CONSTRAINT fkip2kreeti9mgf4tg4gyoxfvca FOREIGN KEY (medico_origem_id) REFERENCES public.medico(id);


--
-- Name: solicitacao fkkbh3bfkb2iiipiwfs2uld4obv; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.solicitacao
    ADD CONSTRAINT fkkbh3bfkb2iiipiwfs2uld4obv FOREIGN KEY (documento_id) REFERENCES public.documento_transferencia(id);


--
-- Name: transferencia fkkkvir0t3qtb9jas4rtqa8ukak; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.transferencia
    ADD CONSTRAINT fkkkvir0t3qtb9jas4rtqa8ukak FOREIGN KEY (origem_id) REFERENCES public.unidade_hospitalar(id);


--
-- Name: medico fkm4iro8s8g0v1rxsgrkb10ya27; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.medico
    ADD CONSTRAINT fkm4iro8s8g0v1rxsgrkb10ya27 FOREIGN KEY (especialidade_id) REFERENCES public.especialidade(id);


--
-- Name: unidade_hospitalar fkmg2wlgd9xoh8o4g986pufo84m; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.unidade_hospitalar
    ADD CONSTRAINT fkmg2wlgd9xoh8o4g986pufo84m FOREIGN KEY (endereco_id) REFERENCES public.endereco(id);


--
-- Name: paciente fkmibfawkbype9v98sv6vhh3015; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.paciente
    ADD CONSTRAINT fkmibfawkbype9v98sv6vhh3015 FOREIGN KEY (prontuario_id) REFERENCES public.prontuario(id);


--
-- Name: unidade_hospitalar_especialidades fkmkqo86gg73iftpn5qt7opkund; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.unidade_hospitalar_especialidades
    ADD CONSTRAINT fkmkqo86gg73iftpn5qt7opkund FOREIGN KEY (especialidade_id) REFERENCES public.especialidade(id);


--
-- Name: medico fkmq8esa4y4l3pwxb9o3k4358p9; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.medico
    ADD CONSTRAINT fkmq8esa4y4l3pwxb9o3k4358p9 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: solicitacao fkmuvrw4451a9v0xh6u7xkdbf2l; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.solicitacao
    ADD CONSTRAINT fkmuvrw4451a9v0xh6u7xkdbf2l FOREIGN KEY (paciente_id) REFERENCES public.paciente(id);


--
-- Name: transferencia fknoinduf39l9w4vsgw5dt7crwd; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.transferencia
    ADD CONSTRAINT fknoinduf39l9w4vsgw5dt7crwd FOREIGN KEY (medico_destino_id) REFERENCES public.medico(id);


--
-- Name: solicitacao fknp7uaump8ry1me7er45vvus8c; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.solicitacao
    ADD CONSTRAINT fknp7uaump8ry1me7er45vvus8c FOREIGN KEY (medico_id) REFERENCES public.medico(id);


--
-- Name: solicitacao_especialidade fko6y6jctntruq86rlbr2sc8t0; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.solicitacao_especialidade
    ADD CONSTRAINT fko6y6jctntruq86rlbr2sc8t0 FOREIGN KEY (especialidade_id) REFERENCES public.especialidade(id);


--
-- Name: prontuario_medicamento_prescrito fkp6k8s4vpg07v5n89v9g5nswus; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.prontuario_medicamento_prescrito
    ADD CONSTRAINT fkp6k8s4vpg07v5n89v9g5nswus FOREIGN KEY (prontuario_id) REFERENCES public.prontuario(id);


--
-- Name: transferencia fkpfpa4vsvrjts6fb57b55xyhut; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.transferencia
    ADD CONSTRAINT fkpfpa4vsvrjts6fb57b55xyhut FOREIGN KEY (destino_id) REFERENCES public.unidade_hospitalar(id);


--
-- Name: paciente fkpus64vtl67yxnw2kimogd7abx; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.paciente
    ADD CONSTRAINT fkpus64vtl67yxnw2kimogd7abx FOREIGN KEY (endereco_id) REFERENCES public.endereco(id);


--
-- Name: medicamento_prescrito fkqfpkj2sxtkx2uy6pnkk6ymqyw; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.medicamento_prescrito
    ADD CONSTRAINT fkqfpkj2sxtkx2uy6pnkk6ymqyw FOREIGN KEY (medicamento_id) REFERENCES public.medicamento(id);


--
-- Name: user_roles fkrhfovtciq1l558cw6udg0h0d3; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fkrhfovtciq1l558cw6udg0h0d3 FOREIGN KEY (role_id) REFERENCES public.role(id);


--
-- Name: transferencia fkro0ju21k3dyjwvxlmnxqxp8o2; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.transferencia
    ADD CONSTRAINT fkro0ju21k3dyjwvxlmnxqxp8o2 FOREIGN KEY (solicitacao_id) REFERENCES public.solicitacao(id);


--
-- Name: transferencia fktgxefl7hxa7yde4tgnqvwunhg; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.transferencia
    ADD CONSTRAINT fktgxefl7hxa7yde4tgnqvwunhg FOREIGN KEY (documento_transferencia_id) REFERENCES public.documento_transferencia(id);


--
-- PostgreSQL database dump complete
--

